language: node_js

node_js:
  - "6.1.x"
  - "6.0.x"
  - "5.11.x"
  - "5.10.x"
  - "5.9.x"
  - "5.8.x"
  - "5.7.x"
  - "5.6.x"
  - "5.5.x"
  - "5.4.x"
  - "5.3.x"
  - "5.2.x"
  - "5.1.x"
  - "5.0.x"
  - "4.4.x"
  - "4.3.x"
  - "4.2.x"
  - "4.1.x"
  - "4.0.x"
  - "0.12.x"
  - "0.11.x"
  - "0.10.x"
  - "0.8.x"
  - "0.6.x"

dist: xenial

env:
  - CC=clang CXX=clang++ npm_config_clang=1

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - clang
